### ISSUE TITLE
Error: Parsing file node_modules/react-fileupload/src/FileUpload.js: Unexpected token (196:16)

### ISSUE THREAD

**Issue by jonashagstedt** [SoAanyip/React-FileUpload#2]
I get this error:

```Error: Parsing file node_modules/react-fileupload/src/FileUpload.js: Unexpected token (196:16)``` (I've removed the full path for brevity).

To replicate:
*  npm install babel babelify --save-dev
*  Add the following to package.json
```"browserify": {
    "transform": [
      [
        "babelify",
        {
          "blacklist": [
            "regenerator"
          ]
        }
      ]
    ]
  }```
*  npm install react-fileupload --save
*  browserify -r react-fileupload

**Comment by SoAanyip** [comment]
I think it is because: I did not write something to guide browserify to the src/FileUpload.js
You can try one of these:
1. Copy FileUpload.js from src to somewhere such as root and try `browserify FileUpload.js`.
2. Or just use the file `dist/main.js`. Change this in node_modules\react-fileupload\package.json : `"main": "dist/main.js"`. This file is in es5 and jsx-transformed.

Maybe you can tell me why it is not work in browserify because I have never used it.

**Comment by jonashagstedt** [comment]
I tried #1 and that worked just fine, thanks
